### ISSUE TITLE
debian 7

### ISSUE THREAD

**Issue by erwbar1** [CoreXDevelopment/NovaMobs#82]
Hello,
I have Debian 7 and i install nukkit to play with my friends on my server. 
Nukkit dont have animals and other mobs, so i try fix it. 
I install this plugin, but dont work and i have this:
[ALERT] java.lang.RuntimeException: java.lang.NullPointerException
at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:450)
at cn.nukkit.Server.enablePlugin(Server.java:627)
at cn.nukkit.Server.enablePlugins(Server.java:616)
at cn.nukkit.Server.reload(Server.java:691)
at cn.nukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:28)
at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:245)
at cn.nukkit.Server.dispatchCommand(Server.java:645)
at cn.nukkit.command.CommandReader.lambda$run$0(CommandReader.java:75)
at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:99)
at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:283)
at cn.nukkit.Server.tick(Server.java:1006)
at cn.nukkit.Server.tickProcessor(Server.java:801)
at cn.nukkit.Server.start(Server.java:780)
at cn.nukkit.Server.(Server.java:471)
at cn.nukkit.Nukkit.main(Nukkit.java:99)
Caused by: java.lang.NullPointerException
at com.pikycz.novamobs.NovaMobs.onEnable(NovaMobs.java:141)
at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89)
at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:113)
at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:446)
... 14 more
please help me, how i can add animals, mobs etc. to my serveer?: (

**Comment by BDZNH** [comment]
maybe you need to type the command when you are playing Minecraft as a op. Instead of type command in the console.
